### ISSUE TITLE
Reset 2016

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#628]
Wake up !
Here are urgent priorities

- [x] Remove "crew" in favor of top contribs #527 #559 #486
- [x] More than 3 post on homepage #569
- [ ] New section #515
- [ ] Nice and easy documentation for contribution #401 and drop the README in favor of link on the website
- [ ] translator on post #585
- [x] Cleanup zepo #590 
- [x] Give write access to all authors #552 
- [ ] Add search bar #535
- [ ] Easy command to merge any PR with a single commit (with possibility to adjust message) https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge, in order to not ask simple pr to get udpated.

**Comment by MoOx** [comment]
(I will update statinamic soon and that will enhance and fixes some bugs)

**Comment by lionelB** [comment]
Once statinamic will be updated, il will give a try to add a search/filter bar

**Comment by magsout** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1997108/12975236/5e91249c-d0ba-11e5-9c4c-a7bffb985d82.gif)

**Comment by magsout** [comment]
We can thinking about a design refresh ? I thought I read that @Nyalab  had some ideas

**Comment by MoOx** [comment]
I don't think it's a urgent priority atm compared to previously raised issues.

**Comment by magsout** [comment]
>I don't think it's a urgent priority atm compared to previously raised issues.

Yeah of course

**Comment by Nyalab** [comment]
we don't care what is urgent or not, just work on what you want/love/hate on p!

**Comment by MoOx** [comment]
![no](https://cloud.githubusercontent.com/assets/157534/12975499/862b54e4-d0bc-11e5-84ae-29c7424a6f54.gif)

**Comment by MoOx** [comment]
@lionelB no blocker with statinamic update. You can start today, no major change from the UI perspective and the way component are used.

**Comment by MoOx** [comment]
That might help http://gitmagic.io/

**Comment by Nyalab** [comment]
this looks nice, i will take a look

**Comment by Nyalab** [comment]
after looking at it, that is something i would use in a professional context, here it would just be some nazi rules (commit/branches formatting, ...), this is no use for us

**Comment by MoOx** [comment]
Important stuff has been handled. We need to continue working one #639.

**Comment by Nyalab** [comment]
hmmm i like this issue, this sums up pretty nicely our next priorities :)

**Comment by MoOx** [comment]
Feel free to pin it to your browser until we handle all issues (I am doing that).
